project_id = "kphwtvbsyfjgzuyaszwp"

[functions.delete-user]
verify_jwt = false

[functions.update-user-email]
verify_jwt = false

[functions.sync-google-sheets]
verify_jwt = false

[functions.auto-reply-support]
verify_jwt = false

[functions.auto-reply-greeting-trigger]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.duplicate-product]
verify_jwt = false
